services:

  db:
    container_name: postgresql
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_procedure_type


  app-be:
    container_name: procedure_type_be
    build:
      context: .
    depends_on:
      - db
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/db_procedure_type
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: 123456

